---- DESIGINING A DATABASE SCHEMA--------
------------------------------------------

------- CREATING A TABLE NAMED AS INDUSTRIES --------
CREATE TABLE Industries (
    industry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_name VARCHAR2(255) NOT NULL,
    description CLOB
);
---------------------------------------------------------

-------- CREATING A TABLE NAMED AS EMISSIONFACTORS -------------
CREATE TABLE EmissionFactors (
    factor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity VARCHAR2(255) NOT NULL,
    emission_factor NUMBER(10, 4) NOT NULL -- tons CO2 per unit activity
);
---------------------------------------------------------------------

--------- CREATING A TABLE NAMED AS EMISSIONS------------------------
CREATE TABLE Emissions (
    emission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_id NUMBER,
    year NUMBER,
    activity VARCHAR2(255),
    activity_level NUMBER(10, 2), -- As an example: MWh, tons, etc.
    emissions NUMBER(10, 4),
    FOREIGN KEY (industry_id) REFERENCES Industries(industry_id)
);
-------------------------------------------------------------------------

----------- INSERTING DATA INTO 1st TABLE--------------------------------
INSERT INTO Industries (industry_name, description) VALUES
('Energy Production', 'Includes fossil fuels and renewable sources.');

INSERT INTO Industries (industry_name, description) VALUES
('Transportation', 'All forms of transport including road and rail.');

INSERT INTO Industries (industry_name, description) VALUES
('Manufacturing', 'Production of goods including heavy and light industries.');

INSERT INTO Industries (industry_name, description) VALUES
('Agriculture', 'Farming, livestock, and related activities.');
-------------------------------------------------------------------------

----------- INSERTING DATA INTO 2nd TABLE--------------------------------
INSERT INTO EmissionFactors (activity, emission_factor) VALUES
('Electricity Generation', 0.0005);  -- tons CO2 per MWh

INSERT INTO EmissionFactors (activity, emission_factor) VALUES
('Truck Transport', 0.01);            -- tons CO2 per ton-mile

INSERT INTO EmissionFactors (activity, emission_factor) VALUES
('Cement Production', 0.8);           -- tons CO2 per ton produced

INSERT INTO EmissionFactors (activity, emission_factor) VALUES
('Rice Cultivation', 0.01);           -- tons CO2 per acre
-------------------------------------------------------------------------

----------- INSERTING DATA INTO 3rd TABLE--------------------------------
INSERT INTO Emissions (industry_id, year, activity, activity_level, emissions) VALUES
(1, 2023, 'Electricity Generation', 10000, 5.0);  -- 10,000 MWh generated

INSERT INTO Emissions (industry_id, year, activity, activity_level, emissions) VALUES
(2, 2023, 'Truck Transport', 2000, 20.0);          -- 2000 ton-miles

INSERT INTO Emissions (industry_id, year, activity, activity_level, emissions) VALUES
(3, 2023, 'Cement Production', 500, 400.0);       -- 500 tons produced

INSERT INTO Emissions (industry_id, year, activity, activity_level, emissions) VALUES
(4, 2023, 'Rice Cultivation', 100, 1.0);           -- 100 acres farmed
-------------------------------------------------------------------------

--------------- DISPLAYING THE DATA OF TOTAL EMISSIONS BY INDUSTRY-------------
SELECT i.industry_name, SUM(e.emissions) AS total_emissions
FROM Emissions e
JOIN Industries i ON e.industry_id = i.industry_id
GROUP BY i.industry_name;
--------------------------------------------------------------------------------

--------------TOTAL EMISSIONS MADE IN A YEAR ----------------------------------
SELECT year, SUM(emissions) AS total_emissions
FROM Emissions
GROUP BY year
ORDER BY year;
-------------------------------------------------------------------------------

-------------- EMISSIONS FOR A PARTICULAR INDUSTRY ----------------------------
SELECT e.year, e.activity, e.emissions
FROM Emissions e
JOIN Industries i ON e.industry_id = i.industry_id
WHERE i.industry_name = 'Energy Production';
-------------------------------------------------------------------------------