------------------- CREATE PARTS TABLE -----------------------------------------
CREATE TABLE Parts (
    part_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50),
    price NUMBER(10, 2) NOT NULL,
    stock_quantity NUMBER NOT NULL
);
--------------------------------------------------------------------------------

----------------- CREATE CUSTOMERS TABLE ---------------------------------------
CREATE TABLE Customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100)
);
--------------------------------------------------------------------------------

------------------------ CREATE SALES TABLE ------------------------------------
CREATE TABLE Sales (
    sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id NUMBER,
    customer_id NUMBER,
    sale_date DATE,
    quantity NUMBER NOT NULL,
    total_amount NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (part_id) REFERENCES Parts(part_id),
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
);
--------------------------------------------------------------------------------

----------------- INSERT DATA INTO PARTS TABLE --------------------------------
INSERT INTO Parts (part_name, category, price, stock_quantity) VALUES ('Brake Pad', 'Brakes', 25.99, 100);
INSERT INTO Parts (part_name, category, price, stock_quantity) VALUES ('Oil Filter', 'Engine', 15.50, 200);
INSERT INTO Parts (part_name, category, price, stock_quantity) VALUES ('Headlight', 'Lighting', 35.00, 50);
INSERT INTO Parts (part_name, category, price, stock_quantity) VALUES ('Tire', 'Wheels', 80.00, 30);

---------------- INSERT DATA INTO CUSTOMERS TABLE ------------------------------
INSERT INTO Customers (first_name, last_name, email) VALUES ('Alex', 'Mercer', 'alex.mercer@example.com');
INSERT INTO Customers (first_name, last_name, email) VALUES ('Lara', 'Croft', 'lara.croft@example.com');
INSERT INTO Customers (first_name, last_name, email) VALUES ('Nathan', 'Drake', 'nathan.drake@example.com');

---------------- INSERT DATA INTO SALES TABLE ----------------------------------
INSERT INTO Sales (part_id, customer_id, sale_date, quantity, total_amount) VALUES (1, 1, TO_DATE('2023-10-01', 'YYYY-MM-DD'), 2, 51.98);
INSERT INTO Sales (part_id, customer_id, sale_date, quantity, total_amount) VALUES (2, 2, TO_DATE('2023-10-02', 'YYYY-MM-DD'), 1, 15.50);
INSERT INTO Sales (part_id, customer_id, sale_date, quantity, total_amount) VALUES (3, 1, TO_DATE('2023-10-03', 'YYYY-MM-DD'), 1, 35.00);
INSERT INTO Sales (part_id, customer_id, sale_date, quantity, total_amount) VALUES (4, 3, TO_DATE('2023-10-04', 'YYYY-MM-DD'), 2, 160.00);

--------------------------------------------------------------------------------

-------------- TOTAL SALES BY PARTS ---------------------------------------
SELECT p.part_name, SUM(s.quantity) AS total_quantity_sold, SUM(s.total_amount) AS total_sales
FROM Parts p
JOIN Sales s ON p.part_id = s.part_id
GROUP BY p.part_name;
--------------------------------------------------------------------------------

-------------------------- SALES BY CUSTOMER -----------------------------------
SELECT c.first_name, c.last_name, SUM(s.total_amount) AS total_spent
FROM Customers c
JOIN Sales s ON c.customer_id = s.customer_id
GROUP BY c.first_name, c.last_name;
--------------------------------------------------------------------------------

----------------------- STOCKS LEVEL FOR PARTS ---------------------------------
SELECT part_name, stock_quantity
FROM Parts
WHERE stock_quantity < 50;
--------------------------------------------------------------------------------

