--------------------- CREATE STUDENTS TABLE -----------------------------------
CREATE TABLE Students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    age NUMBER,
    gender VARCHAR2(10),
    major VARCHAR2(100)
);
-------------------------------------------------------------------------------

--------------------- CREATE MENTALHEALTHASSESSMENTS TABLE ---------------------
CREATE TABLE MentalHealthAssessments (
    assessment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    assessment_date DATE,
    anxiety_score NUMBER CHECK (anxiety_score BETWEEN 0 AND 10),  -- Scale of 0 to 10
    depression_score NUMBER CHECK (depression_score BETWEEN 0 AND 10),  -- Scale of 0 to 10
    stress_score NUMBER CHECK (stress_score BETWEEN 0 AND 10),  -- Scale of 0 to 10
    FOREIGN KEY (student_id) REFERENCES Students(student_id)
);
--------------------------------------------------------------------------------

-------------------- Create SUPPORTSERVICES TABLE ------------------------------
CREATE TABLE SupportServices (
    service_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    service_date DATE,
    service_type VARCHAR2(100),
    notes CLOB,
    FOREIGN KEY (student_id) REFERENCES Students(student_id)
);
-------------------------------------------------------------------------------

--------------- INSERT DATA INTO STUDENTS TABLE --------------------------------
INSERT INTO Students (first_name, last_name, age, gender, major) VALUES ('Alice', 'Smith', 20, 'Female', 'Psychology');
INSERT INTO Students (first_name, last_name, age, gender, major) VALUES ('Bob', 'Johnson', 22, 'Male', 'Engineering');
INSERT INTO Students (first_name, last_name, age, gender, major) VALUES ('Cathy', 'Lee', 19, 'Female', 'Biology');
INSERT INTO Students (first_name, last_name, age, gender, major) VALUES ('David', 'Brown', 21, 'Male', 'History');
--------------------------------------------------------------------------------

---------- INSERT DATA INTO MENTALHEALTHASSESSMENTS TABLE ----------------------
INSERT INTO MentalHealthAssessments (student_id, assessment_date, anxiety_score, depression_score, stress_score) VALUES (1, TO_DATE('2023-10-01', 'YYYY-MM-DD'), 6, 5, 7);
INSERT INTO MentalHealthAssessments (student_id, assessment_date, anxiety_score, depression_score, stress_score) VALUES (2, TO_DATE('2023-10-02', 'YYYY-MM-DD'), 4, 3, 6);
INSERT INTO MentalHealthAssessments (student_id, assessment_date, anxiety_score, depression_score, stress_score) VALUES (3, TO_DATE('2023-10-03', 'YYYY-MM-DD'), 5, 6, 8);
INSERT INTO MentalHealthAssessments (student_id, assessment_date, anxiety_score, depression_score, stress_score) VALUES (4, TO_DATE('2023-10-04', 'YYYY-MM-DD'), 7, 5, 7);
--------------------------------------------------------------------------------

----------- INSERT DATA INTO SUPPORTSSERVICES TABLE ----------------------------
-- Insert data into Students table
INSERT INTO Students (first_name, last_name, age, gender, major) VALUES ('Alice', 'Smith', 20, 'Female', 'Psychology');
INSERT INTO Students (first_name, last_name, age, gender, major) VALUES ('Bob', 'Johnson', 22, 'Male', 'Engineering');
INSERT INTO Students (first_name, last_name, age, gender, major) VALUES ('Cathy', 'Lee', 19, 'Female', 'Biology');
INSERT INTO Students (first_name, last_name, age, gender, major) VALUES ('David', 'Brown', 21, 'Male', 'History');

-- Insert data into MentalHealthAssessments table
INSERT INTO MentalHealthAssessments (student_id, assessment_date, anxiety_score, depression_score, stress_score) VALUES (1, TO_DATE('2023-10-01', 'YYYY-MM-DD'), 6, 5, 7);
INSERT INTO MentalHealthAssessments (student_id, assessment_date, anxiety_score, depression_score, stress_score) VALUES (2, TO_DATE('2023-10-02', 'YYYY-MM-DD'), 4, 3, 6);
INSERT INTO MentalHealthAssessments (student_id, assessment_date, anxiety_score, depression_score, stress_score) VALUES (3, TO_DATE('2023-10-03', 'YYYY-MM-DD'), 5, 6, 8);
INSERT INTO MentalHealthAssessments (student_id, assessment_date, anxiety_score, depression_score, stress_score) VALUES (4, TO_DATE('2023-10-04', 'YYYY-MM-DD'), 7, 5, 7);

-- Insert data into SupportServices table
INSERT INTO SupportServices (student_id, service_date, service_type, notes) VALUES (1, TO_DATE('2023-10-05', 'YYYY-MM-DD'), 'Counseling', 'First session, focused on anxiety management.');
INSERT INTO SupportServices (student_id, service_date, service_type, notes) VALUES (2, TO_DATE('2023-10-06', 'YYYY-MM-DD'), 'Group Therapy', 'Participated in stress management group.');
INSERT INTO SupportServices (student_id, service_date, service_type, notes) VALUES (3, TO_DATE('2023-10-07', 'YYYY-MM-DD'), 'Counseling', 'Discussed coping strategies for depression.');
--------------------------------------------------------------------------------

-------------- AVERAGE SCORES BY MAJOR -----------------------------------------
SELECT s.major,
       AVG(m.anxiety_score) AS avg_anxiety,
       AVG(m.depression_score) AS avg_depression,
       AVG(m.stress_score) AS avg_stress
FROM Students s
JOIN MentalHealthAssessments m ON s.student_id = m.student_id
GROUP BY s.major;
--------------------------------------------------------------------------------

----------------- STUDENTS NEEDING SUPPORT -------------------------------------
SELECT s.first_name, s.last_name, m.assessment_date, 
       m.anxiety_score, m.depression_score, m.stress_score
FROM Students s
JOIN MentalHealthAssessments m ON s.student_id = m.student_id
WHERE m.anxiety_score > 5 OR m.depression_score > 5 OR m.stress_score > 5;
--------------------------------------------------------------------------------

------------ SUPPORT SERVICES UTILIZATION --------------------------------------
SELECT s.first_name, s.last_name, COUNT(ss.service_id) AS services_used
FROM Students s
LEFT JOIN SupportServices ss ON s.student_id = ss.student_id
GROUP BY s.first_name, s.last_name;
--------------------------------------------------------------------------------
